Removed error exit when not building image.

diff --git a/grunt/shell.yaml b/grunt/shell.yaml
--- a/grunt/shell.yaml
+++ b/grunt/shell.yaml
@@ -5,8 +5,9 @@ bookmarklet:
 clean-build: rm -rf dist
 docker-build:
     command: |
-        which docker > /dev/null || { echo 'Docker client not found. Not building image. Build the image outside Grunt.'; exit 1; }
+        which docker > /dev/null || { echo 'Docker client not found. Not building image. Build the image outside Grunt.'; return; }
         if [ -z $DOCKER_TAG ]; then 
-            echo "DOCKER_TAG environment variable not found. Not building image. Add a DOCKER_TAG value inside the .env file."; exit 1; 
+            echo "DOCKER_TAG environment variable not found. Not building image. Add a DOCKER_TAG value inside the .env file."
+            return
         fi &&
         docker build --tag $DOCKER_IMAGE:$DOCKER_TAG .
