Added check for Docker and the tag before building image in Grunt.

diff --git a/grunt/shell.yaml b/grunt/shell.yaml
--- a/grunt/shell.yaml
+++ b/grunt/shell.yaml
@@ -5,7 +5,8 @@ bookmarklet:
 clean-build: rm -rf dist
 docker-build:
     command: |
-        echo $TAG &&
-        which docker &&
-        if [ -z ${TAG+x} ]; then TAG=`git describe --abbrev=0 --tags`; fi &&
-        docker build --tag batandwa/just-the-video:$TAG .
+        which docker > /dev/null || { echo 'Docker client not found. Not building image. Build the image outside Grunt.'; exit 1; }
+        if [ -z $DOCKER_TAG ]; then 
+            echo "DOCKER_TAG environment variable not found. Not building image. Add a DOCKER_TAG value inside the .env file."; exit 1; 
+        fi &&
+        docker build --tag $DOCKER_IMAGE:$DOCKER_TAG .
